version: '2'
services:

  ohiovoter:
    build: .
    working_dir: /opt/ohiovoter/
    volumes:
      - .:/opt/ohiovoter
    environment:
      - DJANGO_SETTINGS_MODULE=ohiovoter.settings
      - DB_NAME=ohiovoter
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=ohiovoter
      - DB_PORT=5432
